# Site
repository: SyGwasTaken/sysamson.github.io

favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sen Yuan B. Samson
title: Game Designer
email: senyuansamson17@gmail.com
website: www.github.com/SyGwasTaken/sysamson.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  SyGwasTaken
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
youtube_username: https://www.youtube.com/channel/UCKC1P9sOsQU_GpWH8HbTAVw
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: facebook.com/Sy.Gaming17
  icon: fab fa-facebook https://fontawesome.com/icons/facebook?s=solid&f=brands
  url: https://www.facebook.com/gaming/Sy.Gaming17
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sen Yuan and I'm currently a game designer. As well as a streamer I also have experience making software and web apps. I'm working at a company gaining teamwork and leadership skills.

  I am most skilled in: <mark>coding</mark> and <mark>drawing</mark>

content:
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bongabon National High School
        caption: 2016-2022
        sub_title: STE & STEM
        
        title: Lyceum of the Philippines University - Manila
        caption: 2022-2026
        sub_title: BS Esports Game Design and Development
        description: | # this will include new lines to allow paragraphs
          During my time at LPU Manila I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time in the university and learnt a lot about a healthy work life balance.
      
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in game designing and software engineering some of my other interests and hobbies are:
      - Reading
      - Gaming
      - Basketball

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
